### ISSUE TITLE
cifar10 pretrain_weights

### ISSUE THREAD

**Issue by Kris-Lcq** [CHENBIN99/AdaEA#1]
The author has done a great job, greatly accelerating the transferability of adversarial examples. I would like to ask if the author can provide pretraining weights for all models on Cifar10. Thank you very much.

**Comment by CHENBIN99** [comment]
Thank you for your attention to this work! We release the weights of the cifar10 model used in this paper, which can be accessed in the [Google Cloud Drive](https://drive.google.com/drive/folders/19z1Sd-FFC2rGFkc93lqVDbmHcxBxZlNt?usp=sharing)
