### ISSUE TITLE
关于ImageNet的预训练模型的问题

### ISSUE THREAD

**Issue by Clouds06** [CHENBIN99/AdaEA#11]
作者您好！当数据集设置为CIFAR-10/100时，可以获得与原文相近的实验结果。但当数据集设置为ImageNet时，预训练模型的原始准确率（Nat. Acc.）和对抗准确率（Adv. Acc.）都在0.1%以下，请问这是什么问题呢？
![imagenet](https://github.com/CHENBIN99/AdaEA/assets/99071084/bc9622b7-75a7-41c1-9ee7-fa87eac83e91)

**Comment by CHENBIN99** [comment]
我觉得应该检查在ImageNet的情况下，各个模型的权重是否正确的读取了

**Comment by xhx1022** [comment]
@CHENBIN99 您好，我也是出现这个问题，已经下载了验证集，并检查timm已经成功下载了模型，也成功读取了，但还是出现这个问题，请问除了改attack.py中的dataset参数为imagenet，还有哪些需要改动的吗

**Comment by Clouds06** [comment]
@CHENBIN99 好的谢谢您！问题已解决
