### ISSUE TITLE
关于模型梯度相似性的问题

### ISSUE THREAD

**Issue by Clouds06** [CHENBIN99/AdaEA#12]
作者您好！请问在求不同代理模型梯度的余弦相似性时，是否会有模型之间的梯度维度不一致的问题？
根据提供的源代码，DRF中使用torch.nn.CosineSimilarity求余弦相似性，其中的张量广播机制可以将低维张量自动转化为高维张量。但广播机制也有一些无法处理的情况，请问在DRF中是否会遇到这种情况？还是说广播机制就足够解决DRF中可能出现的模型梯度维度不一致的问题？

**Comment by CHENBIN99** [comment]
求出的梯度与输入图片的尺寸一致，不同模型之间不存在尺寸不一样的问题
