### ISSUE TITLE
Questions about small details in the code

### ISSUE THREAD

**Issue by Caocious** [CHENBIN99/AdaEA#2]
1.In the /utils/get_models.py file, line 10 mentions "adv_yaml_path = 'checkpoint_adv.yaml'", but there is no checkpoint_adv.yaml file in your files, and the adv_yaml_path variable is not used in the get_models.py file. Is this an oversight?
2.In the attack.py file, the args parameter does not have the no_agm and no_drf options, but the get_attack function in the /utils/get_attack.py file uses args.no_agm and args.no_drf as parameters. Should this inconsistency be corrected?
3.How can I download the pre-trained weights mentioned in the Readme file and put them into the following directory: "./checkpoint_file/cifar10/" and "./checkpoint_file/cifar100"? 
Thank you!

**Comment by CHENBIN99** [comment]
1. `checkpoint_adv.yaml` and `adv_yaml_path` are the file and variable used to perform the attacks on the adversarial robust model in the paper, which were not removed in the final version, but do not affect the code.
2. Thank you for your attention, the unnecessary code has been removed.
3. The pretrained model has been uploaded, which can be access in [Google Drive](https://drive.google.com/drive/folders/19z1Sd-FFC2rGFkc93lqVDbmHcxBxZlNt?usp=sharing). #1 
4. Issue is enough, there is no need to send an email to each author.

**Comment by Caocious** [comment]
Thank you very much for your answer. If my interruption has caused any inconvenience to you, I sincerely apologize.

**Comment by Caocious** [comment]
> 1. `checkpoint_adv.yaml` and `adv_yaml_path` are the file and variable used to perform the attacks on the adversarial robust model in the paper, which were not removed in the final version, but do not affect the code.
> 2. Thank you for your attention, the unnecessary code has been removed.
> 3. The pretrained model has been uploaded, which can be access in [Google Drive](https://drive.google.com/drive/folders/19z1Sd-FFC2rGFkc93lqVDbmHcxBxZlNt?usp=sharing). [cifar10 pretrain_weights #1](https://github.com/CHENBIN99/AdaEA/issues/1)
> 4. Issue is enough, there is no need to send an email to each author.

Thank you very much for your answer. If my interruption has caused any inconvenience to you, I sincerely apologize.
