### ISSUE TITLE
pretrained-weight issue

### ISSUE THREAD

**Issue by Pianyu666** [CHENBIN99/AdaEA#4]
The pre-trained model weights are missing, for example, for surrogate models such as 'resnet18', 'inc_v3', 'vit_t', 'deit_t'. Is it possible to upload them? Thank you!

**Comment by anuin-cat** [comment]
I have the same need, and although it is easy to fine-tune the pre-training to get a relevant model, there is a big gap in the results, and it seems that this method doesn't work in cifar10 as well as cifar100

**Comment by CHENBIN99** [comment]
We have uploaded the weights of the models you mentioned, you can get them from this [link](https://drive.google.com/drive/folders/19z1Sd-FFC2rGFkc93lqVDbmHcxBxZlNt?usp=sharing)
