### ISSUE TITLE
There seems to be an error in equation (7) in the paper

### ISSUE THREAD

**Issue by anuin-cat** [CHENBIN99/AdaEA#6]
![image](https://github.com/CHENBIN99/AdaEA/assets/59217038/4fcbf0df-17d7-494d-8a81-29bef4c0c584)
There seems to be an error in equation (7) in the paper, the subscript i for d should be removed, as the original text states that “The
final disparity map d for ensemble gradients is obtained by averaging all the di.”

Maybe the picture below is the correct version
![image](https://github.com/CHENBIN99/AdaEA/assets/59217038/473810d0-6550-40ab-afe7-26a7ef4d4fdc)

**Comment by CHENBIN99** [comment]
Thank you for your question, we will check this issue
