### ISSUE TITLE
关于数据集图像大小问题，

### ISSUE THREAD

**Issue by linghuchong111da** [CHENBIN99/AdaEA#8]
作者你好，请问在cifar10和cifar100的时候，数据集图像大小设置为32的时候，inception_v3模型会出现问题，图像大小只有设置成224的时候才能跑

**Comment by CHENBIN99** [comment]
你好，我们所提供的CIFAR10/100的权重为TIMM中ImageNet数据集上的预训练模型微调而来，我们并未修改除最后的全连接层以外的网络结构，所以对于这些模型都需要调整图片大小为224才能正常工作
