### ISSUE TITLE
run cifar100 dataset error

### ISSUE THREAD

**Issue by xhx1022** [CHENBIN99/AdaEA#9]
When I run the cifar100 dataset on bit50_1 and swin_b, I encounter the following error message. How can I resolve it?  
RuntimeError: Error(s) in loading state_dict for ResNet:
        size mismatch for fc.weight: copying a param with shape torch.Size([100, 2048]) from checkpoint, the shape in the current model is torch.Size([10, 2048]).
        size mismatch for fc.bias: copying a param with shape torch.Size([100]) from checkpoint, the shape in the current model is torch.Size([10]).

**Comment by xhx1022** [comment]
@CHENBIN99 The error is occurring specifically with the two pre-trained models, bit50_1 and swin_b, while the others are not encountering any issues. What could be the reason for this?

**Comment by linghuchong111da** [comment]
你好，请问你解决了这个问题吗，我在cifar100数据集上也遇到了这个问题

**Comment by linghuchong111da** [comment]
> @CHENBIN99该错误特别发生在两个预训练模型 bit50_1 和 swin_b 上，而其他模型则没有遇到任何问题。这可能是什么原因？

I met this problem,did you solve it?
